
rm COUNTY_NAMES.txt
cat KY_COUNTY_NAMES_UNI.txt >> COUNTY_NAMES.txt
cat OH_COUNTY_NAMES_UNI.txt >> COUNTY_NAMES.txt
cat PA_COUNTY_NAMES_UNI.txt >> COUNTY_NAMES.txt
cat VA_COUNTY_NAMES_UNI.txt >> COUNTY_NAMES.txt
cat WV_COUNTY_NAMES_UNI.txt >> COUNTY_NAMES.txt
wc COUNTY_NAMES.txt
