rm DRUG_COUNTS.txt

cat 2010_DRUG_COUNTS_UNI.txt >> DRUG_COUNTS.txt
cat 2011_DRUG_COUNTS_UNI.txt >> DRUG_COUNTS.txt
cat 2012_DRUG_COUNTS_UNI.txt >> DRUG_COUNTS.txt
cat 2013_DRUG_COUNTS_UNI.txt >> DRUG_COUNTS.txt
cat 2014_DRUG_COUNTS_UNI.txt >> DRUG_COUNTS.txt
cat 2015_DRUG_COUNTS_UNI.txt >> DRUG_COUNTS.txt
cat 2016_DRUG_COUNTS_UNI.txt >> DRUG_COUNTS.txt
cat 2017_DRUG_COUNTS_UNI.txt >> DRUG_COUNTS.txt


